theme: minima

title: Irene Rivera Calde
description: Sabbatical learnings; miscellaneous interesting things. "<em>No se cuentan los segundos, se cuentan historias</em>"

url: "https://www.irehneh.com"  # replace with your actual domain

# These are required for the theme to work
plugins:
  - jekyll-feed
