theme: minima

title: Irene Rivera Calderon
description: Sabbatical learnings & miscellaneous interesting things

url: "https://www.irehneh.com"  # replace with your actual domain

# These are required for the theme to work
plugins:
  - jekyll-feed
